### ISSUE TITLE
Doesn't work with snap (?)

### ISSUE THREAD

**Issue by keunes** [gaqzi/chrome-open-in-spotify-client#3]
I have installed Spotify on Ubuntu 18.04 via the OS's store, which by default now installs a snap. There's two issues I'm experiencing, which may have to do with the fact that it's a snap:
- the plugin launches a new Spotify instance every time a link is opened (instead of using the existing spotify instance)
- the right playlist/album/artist isn't opened; it just launches Spotify's home screen

Not sure if you're able to support this at all, or if this would require action from Spotify's side. Thanks in any case for your work on this :)

**Comment by gaqzi** [comment]
Sorry, I don't use Linux as a desktop so I can't help out there :x 

(plus I'm guessing 1.5 years down the line it's not overly interesting to get a response either, but hey, I wanted to burn down the open issues :p
