### ISSUE TITLE
Spotify web link not working

### ISSUE THREAD

**Issue by shape55** [gaqzi/chrome-open-in-spotify-client#5]
https://www.whosampled.com/sample/66079/Amon-Tobin-People-Like-Frank-Angelo-Badalamenti-Night-Streets-Sandy-and-Jeffrey/

Hi, just letting you know I'm not able to get this link to load in Spotify.  The track on the right by Angelo Badalamenti has a Spotify link but will neither play in Chrome nor open the desktop app.

**Comment by gaqzi** [comment]
I think this will be solved with the release of 1.4.1, which is pending review, because it addresses more versions of embedded links that the extension ignores.
